FROM node:12.0.0

# create app directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn

# Bundle app source
COPY . .

# yarn build
RUN yarn build

# expose port
EXPOSE ${PORT}
CMD ["yarn", "serve"]