FROM node:11.15.0

# create app directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn --frozen-lockfile

# Bundle app source
COPY . .

# run build
RUN yarn build

EXPOSE 7077
CMD ["yarn", "start"]