FROM node:11.15.0
RUN curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.26.1

# create app directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn

# Bundle app source
COPY . .

# run build
RUN yarn build

EXPOSE 7077
CMD ["yarn", "start"]