FROM node:12.0.0

# create app directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn

# Bundle app source
COPY . .

# run build
RUN yarn build

EXPOSE 7077
CMD ["yarn", "start"]